remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
- jekyll-remote-theme

title: Odin Vulkan Tutorial
description: Learning Vulkan from scratch with Odin — step-by-step, no bootstrap, explained by hand.

color_scheme: dark

search_enabled: true
heading_anchors: true

aux_links:
  "Source on GitHub":
    - "//github.com/Hilderin/OdinVulkan"

footer_content: "Odin Vulkan Tutorial &copy; 2026. Distributed by an MIT license."

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Hilderin/OdinVulkan"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: green
